### ISSUE TITLE
Segfault on texture load

### ISSUE THREAD

**Issue by Froloket64** [irishgreencitrus/raylib.v#2]
When I call `load_texture()` my game crashes.
The image is just black (#000) rect of 150x275 pixels.

Code: https://pastebin.com/CkdFKwFi 

Output:
```
INFO: FILEIO: [test.png] File loaded successfully
INFO: IMAGE: Data loaded successfully (150x275 | R8G8B8A8 | 1 mipmaps)
signal 11: segmentation fault
```

V version: V 0.3.0 f75d7eb _(latest by now)_

**Comment by SomeUnusualGames** [comment]
You have to call `init_window` first before loading any texture.

**Comment by Froloket64** [comment]
Oh, I see, thanks
